doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # driver: pdo_mysql
        # host: "%database_host%"
        # port: "%database_port%"
        # dbname: "%database_name%"
        # user: "%database_user%"
        # password: "%database_password%"
        charset: utf8mb4
        server_version: 5.7
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        # backtrace queries in profiler (increases memory usage per request)
        profiling_collect_backtrace: '%kernel.debug%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
