language: php

services:
    - rabbitmq
    - redis

sudo: false

cache:
    apt: true
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: CS_FIXER=run
        - php: 7.0
        - php: 7.1
        - php: nightly
    allow_failures:
        - php: nightly

install:
    - composer --prefer-dist install --no-interaction

before_script:
    - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - ./bin/console doctrine:database:create
    - ./bin/console doctrine:schema:create
    - ./bin/rabbit vhost:mapping:create -p guest app/config/rabbit_vhost.yml

script:
    - ./bin/simple-phpunit -v
    - if [ "$CS_FIXER" = "run" ]; then php bin/php-cs-fixer fix --verbose --dry-run ; fi;
