imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ["%locale%"] }
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: "%locale%"
    trusted_hosts: ~
    session:
        name: banditore
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: utf8mb4
        server_version: 5.7
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/migrations"
    name: Banditore Migrations

knpu_oauth2_client:
    clients:
        # will create service: "knpu.oauth2.client.github"
        # an instance of: KnpU\OAuth2ClientBundle\Client\Provider\GithubClient
        github:
            type: github
            client_id: "%github_client_id%"
            client_secret: "%github_client_secret%"
            # a route name you'll create
            redirect_route: github_callback
            redirect_params: {}

swarrot:
    provider: amqp_lib # pecl or amqp_lib
    connections:
        rabbitmq:
            host: '%rabbitmq_host%'
            port: '%rabbitmq_port%'
            login: '%rabbitmq_login%'
            password: '%rabbitmq_password%'
            vhost: '/'
    consumers:
        banditore.sync_starred_repos:
            processor: banditore.consumer.sync_starred_repos
            extras:
                poll_interval: 500000
            middleware_stack:
                - configurator: swarrot.processor.new_relic
                  extras:
                      new_relic_app_name: banditore
                - configurator: swarrot.processor.max_messages
                  extras:
                      max_messages: 5
                - configurator: swarrot.processor.doctrine_connection
                - configurator: swarrot.processor.retry
                - configurator: swarrot.processor.exception_catcher
                - configurator: swarrot.processor.ack
        banditore.sync_versions:
            processor: banditore.consumer.sync_versions
            extras:
                poll_interval: 500000
            middleware_stack:
                - configurator: swarrot.processor.new_relic
                  extras:
                      new_relic_app_name: banditore
                # stop workers after 50 messages to avoid eating too much memory
                - configurator: swarrot.processor.max_messages
                  extras:
                      max_messages: 50
                - configurator: swarrot.processor.doctrine_connection
                - configurator: swarrot.processor.retry
                - configurator: swarrot.processor.exception_catcher
                - configurator: swarrot.processor.ack
    messages_types:
        banditore.sync_starred_repos.publisher:
            connection: rabbitmq
            exchange: banditore.sync_starred_repos
        banditore.sync_versions.publisher:
            connection: rabbitmq
            exchange: banditore.sync_versions

ashley_dawson_simple_pagination:
    defaults:
        items_per_page: 30
        pages_in_range: 5
        template: default/_pagination.html.twig

snc_redis:
    clients:
        guzzle_cache:
            type: predis
            alias: guzzle_cache
            dsn: "%redis_dsn_guzzle_cache%"
        doctrine_cache:
            type: predis
            alias: doctrine_cache
            dsn: "%redis_dsn_doctrine_cache%"

# fix default options to remove a deprecated notif
# > The \Raven_SanitizeDataProcessor class is deprecated since version 1.7 and will be removed in 2.0. Use the Raven_Processor_SanitizeDataProcessor class in the same namespace instead
# https://github.com/getsentry/sentry-symfony/commit/4d34147b55c53aefa0c5378da37b14247ae5cd9e
sentry:
    options:
        processors:
            - Raven_Processor_SanitizeDataProcessor

# see https://github.com/symfony/symfony-standard/pull/1133
sensio_framework_extra:
   router:
        annotations: false
