imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: streamed_main
        streamed_main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false

sentry:
    dsn: "%sentry_dsn%"

snc_redis:
    doctrine:
        metadata_cache:
            client: doctrine_cache
            entity_manager: default
        result_cache:
            client: doctrine_cache
            entity_manager: default
        query_cache:
            client: doctrine_cache
            entity_manager: default
