imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped_main
        grouped_main:
            type: group
            members: [streamed_main, sentry]
        streamed_main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        sentry:
            type: raven
            dsn: "%sentry_dsn%"
            level: error
        console:
            type: console

sentry:
    dsn: "%sentry_dsn%"

ekino_new_relic:
    enabled: true

snc_redis:
    doctrine:
        metadata_cache:
            client: doctrine_cache
            entity_manager: default
        result_cache:
            client: doctrine_cache
            entity_manager: default
        query_cache:
            client: doctrine_cache
            entity_manager: default
