imports:
    - { resource: config_dev.yml }
    - { resource: services_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        driver: pdo_mysql
        host: "127.0.0.1"
        port: ~
        dbname: "banditore_test"
        user: "root"
        password: ~
        charset: utf8mb4

web_profiler:
    toolbar: false
    intercept_redirects: false

parameters:
    swarrot.publisher.class: Swarrot\SwarrotBundle\Broker\BlackholePublisher
