security:
    providers:
        github_provider:
            entity:
                class: AppBundle:User
                property: githubId

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            anonymous: ~
            logout: ~

            guard:
                authenticators:
                    - AppBundle\Security\GithubAuthenticator
