services:
    banditore.client.guzzle:
        class: GuzzleHttp\Client

    banditore.github.authenticator:
        class: AppBundle\Security\GithubAuthenticator
        arguments:
            - "@knpu.oauth2.registry"
            - "@doctrine.orm.default_entity_manager"
            - "@router"
            - "@swarrot.publisher"

    banditore.client.redis:
        class: Redis
        calls:
            - [ connect, [ "%redis_host%", "%redis_port%" ] ]
            - [ select, [ "%redis_database%" ] ]

    # repository as a service
    banditore.repository.repo:
        class: AppBundle\Repository\RepoRepository
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
        arguments:
            - AppBundle:Repo

    banditore.repository.star:
        class: AppBundle\Repository\StarRepository
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
        arguments:
            - AppBundle:Star

    banditore.repository.user:
        class: AppBundle\Repository\UserRepository
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
        arguments:
            - AppBundle:User

    banditore.repository.version:
        class: AppBundle\Repository\VersionRepository
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
        arguments:
            - AppBundle:Version

    # global Github application client
    banditore.client.github.application:
        class: Github\Client
        calls:
            - [ authenticate, [ "%github_client_id%", "%github_client_secret%", !php/const:Github\Client::AUTH_URL_CLIENT_ID ] ]

    banditore.writer.webfeeds:
        class: AppBundle\Webfeeds\WebfeedsWriter
        tags:
            - { name: marcw_rss_writer.extension.writer }

    banditore.writer.rss:
        class: MarcW\RssWriter\RssWriter
        arguments:
            - ~
            -
                core: "@marcw_rss_writer.writer.core"
                webfeeds: "@banditore.writer.webfeeds"
                atom: "@marcw_rss_writer.writer.atom"
            - true
            - "    "

    banditore.pubsubhubbub.publisher:
        class: AppBundle\PubSubHubbub\Publisher
        arguments:
            - "http://pubsubhubbub.appspot.com"
            - "@router"
            - "@banditore.client.guzzle"
            - "@banditore.repository.user"
            - "%project_host%"
            - "%project_scheme%"

    # consumers
    banditore.consumer.sync_user_repo:
        class: AppBundle\Consumer\SyncUserRepo
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@banditore.repository.user"
            - "@banditore.repository.star"
            - "@banditore.repository.repo"
            - "@logger"
