services:
    # fixtures
    AppBundle\DataFixtures\ORM\:
        resource: '../../src/AppBundle/DataFixtures/ORM/*'
        tags: ['doctrine.fixture.orm']
        autowire: true

    # see https://github.com/symfony/symfony/issues/24543
    banditore.repository.user.test:
        alias: AppBundle\Repository\UserRepository
        public: true

    banditore.repository.version.test:
        alias: AppBundle\Repository\VersionRepository
        public: true

    banditore.repository.repo.test:
        alias: AppBundle\Repository\RepoRepository
        public: true

    banditore.repository.star.test:
        alias: AppBundle\Repository\StarRepository
        public: true

    banditore.consumer.sync_versions.test:
        alias: banditore.consumer.sync_versions
        public: true

    banditore.consumer.sync_starred_repos.test:
        alias: banditore.consumer.sync_starred_repos
        public: true

    banditore.github.client_discovery.test:
        alias: banditore.github.client_discovery
        public: true

    banditore.client.guzzle.test:
        alias: banditore.client.guzzle
        public: true

    banditore.client.github.test:
        alias: banditore.client.github
        public: true
