services:
    banditore.client.guzzle:
        class: GuzzleHttp\Client

    banditore.github.authenticator:
        class: AppBundle\Security\GithubAuthenticator
        arguments:
            - "@knpu.oauth2.registry"
            - "@doctrine.orm.default_entity_manager"
            - "@router"
            - "@swarrot.publisher"

    # repository as a service
    banditore.repository.repo:
        class: AppBundle\Repository\RepoRepository
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
        arguments:
            - AppBundle:Repo

    banditore.repository.star:
        class: AppBundle\Repository\StarRepository
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
        arguments:
            - AppBundle:Star

    banditore.repository.user:
        class: AppBundle\Repository\UserRepository
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
        arguments:
            - AppBundle:User

    banditore.repository.version:
        class: AppBundle\Repository\VersionRepository
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
        arguments:
            - AppBundle:Version

    banditore.client.github:
        class: Github\Client
        factory: [ "@banditore.github.client_discovery", find ]

    banditore.github.client_discovery:
        class: AppBundle\Github\ClientDiscovery
        arguments:
            - "@banditore.repository.user"
            - "@snc_redis.guzzle_cache"
            - "%github_client_id%"
            - "%github_client_secret%"
            - "@logger"

    banditore.writer.webfeeds:
        class: AppBundle\Webfeeds\WebfeedsWriter
        tags:
            - { name: marcw_rss_writer.extension.writer }

    banditore.writer.rss:
        class: MarcW\RssWriter\RssWriter
        arguments:
            - ~
            -
                core: "@marcw_rss_writer.writer.core"
                webfeeds: "@banditore.writer.webfeeds"
                atom: "@marcw_rss_writer.writer.atom"
            - true
            - "    "

    banditore.pubsubhubbub.publisher:
        class: AppBundle\PubSubHubbub\Publisher
        arguments:
            - "http://pubsubhubbub.appspot.com"
            - "@router"
            - "@banditore.client.guzzle"
            - "@banditore.repository.user"
            - "%project_host%"
            - "%project_scheme%"

    banditore.rss.generator:
        class: AppBundle\Rss\Generator

    # consumers
    banditore.consumer.sync_starred_repos:
        class: AppBundle\Consumer\SyncStarredRepos
        arguments:
            - "@doctrine"
            - "@banditore.repository.user"
            - "@banditore.repository.star"
            - "@banditore.repository.repo"
            - "@banditore.client.github"
            - "@logger"
        # to avoid triggering Github Client Discovery
        # which will make a doctrine query on Travis because the default limit to Github will be reached
        lazy: true

    banditore.consumer.sync_versions:
        class: AppBundle\Consumer\SyncVersions
        arguments:
            - "@doctrine"
            - "@banditore.repository.repo"
            - "@banditore.repository.version"
            - "@banditore.pubsubhubbub.publisher"
            - "@banditore.client.github"
            - "@logger"
        # to avoid triggering Github Client Discovery
        # which will make a doctrine query on Travis because the default limit to Github will be reached
        lazy: true

    # twig extensions
    banditore.twig_extension.repo_version:
        class: AppBundle\Twig\RepoVersionExtension
        public: false
        tags:
            - { name: twig.extension }

    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }
