'/':
    parameters:
        # If true, all queues will have a dl and the corresponding mapping with the exchange "dl"
        with_dl: false
        # If true, all exchange will be declared with an unroutable config
        with_unroutable: false

    exchanges:
        banditore.sync_starred_repos:
            type: direct
            durable: true
        banditore.sync_versions:
            type: direct
            durable: true

    queues:
        banditore.sync_starred_repos:
            durable: true
            bindings:
                - exchange: banditore.sync_starred_repos
        banditore.sync_versions:
            durable: true
            bindings:
                - exchange: banditore.sync_versions
