services:
    # see https://github.com/symfony/symfony/issues/24543
    banditore.client.github.test:
        alias: banditore.client.github
        public: true

    banditore.client.guzzle.test:
        alias: banditore.client.guzzle
        public: true
