name: "CI"

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

env:
  fail-fast: true
  APP_ENV: test

jobs:
  phpunit:
    name: "PHPUnit (PHP ${{ matrix.php }})"
    runs-on: "ubuntu-20.04"
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
      rabbitmq:
        image: rabbitmq:3-alpine
        ports:
          - 5672:5672
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379

    strategy:
      matrix:
        php:
          - "7.2"
          - "7.3"
          - "7.4"
        include:
          - php: "7.4"
            coverage: true

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP with PCOV"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          coverage: "pcov"
          tools: composer:v2
          extensions: pdo, pdo_mysql, curl, redis, amqp
          ini-values: "date.timezone=Europe/Paris"
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--optimize-autoloader --prefer-dist"

      - name: "Create database"
        run: "php bin/console doctrine:database:create --env=test"

      - name: "Create schema"
        run: "php bin/console doctrine:schema:create --env=test"

      - name: "Load fixtures"
        run: "php bin/console doctrine:fixtures:load --env=test -n"

      - name: "Setup messenger queue"
        run: "php bin/console messenger:setup-transports --env=dev"

      - name: "Run PHPUnit (with coverage)"
        run: "php bin/simple-phpunit -v --coverage-clover=coverage.xml"
        if: matrix.coverage

      - name: "Run PHPUnit"
        run: "php bin/simple-phpunit -v"
        if: "${{ !matrix.coverage }}"

      - name: "Retrieve Coveralls phar"
        if: matrix.coverage
        run: "wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.2/php-coveralls.phar"

      - name: "Enable Coveralls phar"
        if: matrix.coverage
        run: "chmod +x php-coveralls.phar"

      - name: "Upload to Coveralls"
        if: matrix.coverage
        run: "php php-coveralls.phar -v -x coverage.xml -o coveralls-upload.json"
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
